import { PrismaClient } from "@prisma/client";

const prisma = new PrismaClient();

const starterRecipes = [
  [
    "Tigela de aveia com frutas",
    "Café da manhã",
    ["Rápido", "Alta proteína"],
    420,
    10,
    ["Aveia em flocos", "Iogurte natural", "Banana", "Morangos", "Chia"],
    [
      "Misture a aveia e o iogurte.",
      "Cubra com as frutas.",
      "Finalize com chia e sirva.",
    ],
  ],
  [
    "Salada de grão-de-bico",
    "Almoço",
    ["Vegetariano", "Sem glúten"],
    520,
    20,
    [
      "Grão-de-bico cozido",
      "Tomate",
      "Pepino",
      "Cebola roxa",
      "Azeite",
      "Limão",
    ],
    ["Corte os vegetais.", "Misture com o grão-de-bico.", "Tempere e sirva."],
  ],
  [
    "Frango grelhado com quinoa",
    "Jantar",
    ["Alta proteína", "Baixo custo"],
    610,
    30,
    ["Peito de frango", "Quinoa", "Brócolis", "Alho", "Azeite"],
    [
      "Tempere o frango.",
      "Grelhe até cozinhar.",
      "Sirva com quinoa e brócolis.",
    ],
  ],
  [
    "Iogurte com granola",
    "Lanche",
    ["Rápido", "Sem lactose"],
    330,
    5,
    ["Iogurte natural", "Granola", "Banana", "Canela"],
    [
      "Coloque o iogurte em uma tigela.",
      "Adicione granola e banana.",
      "Finalize com canela.",
    ],
  ],
  [
    "Omelete com abacate",
    "Café da manhã",
    ["Low carb", "Saturado"],
    390,
    12,
    ["Ovos", "Abacate", "Tomate", "Cebolinha", "Azeite"],
    [
      "Bata e tempere os ovos.",
      "Cozinhe até firmar.",
      "Sirva com abacate e tomate.",
    ],
  ],
  [
    "Wrap de frango e salada",
    "Almoço",
    ["Leve", "Prático"],
    540,
    15,
    [
      "Tortilha integral",
      "Frango desfiado",
      "Alface",
      "Tomate",
      "Iogurte natural",
    ],
    ["Aqueça a tortilha.", "Recheie com frango e salada.", "Enrole e sirva."],
  ],
  [
    "Peixe ao forno com legumes",
    "Jantar",
    ["Fácil", "Proteína"],
    640,
    28,
    ["Filé de peixe", "Abobrinha", "Cenoura", "Limão", "Azeite"],
    ["Tempere o peixe.", "Disponha com os legumes.", "Asse até ficar macio."],
  ],
  [
    "Smoothie verde com banana",
    "Lanche",
    ["Rápido", "Natural"],
    290,
    5,
    ["Banana", "Couve", "Leite ou bebida vegetal", "Aveia", "Gengibre"],
    ["Lave a couve.", "Bata todos os ingredientes.", "Sirva imediatamente."],
  ],
  [
    "Pão integral com ovos",
    "Café da manhã",
    ["Fácil", "Sustentável"],
    410,
    10,
    ["Pão integral", "Ovos", "Tomate", "Folhas verdes"],
    ["Prepare os ovos.", "Toste o pão.", "Monte e sirva."],
  ],
  [
    "Bowl de quinoa e legumes",
    "Almoço",
    ["Completo", "Sem glúten"],
    560,
    18,
    ["Quinoa", "Abobrinha", "Cenoura", "Grão-de-bico", "Azeite"],
    ["Cozinhe a quinoa.", "Refogue os legumes.", "Misture e tempere."],
  ],
  [
    "Salmão com arroz integral",
    "Jantar",
    ["Omega 3", "Forte"],
    700,
    35,
    ["Filé de salmão", "Arroz integral", "Limão", "Brócolis", "Azeite"],
    ["Tempere o salmão.", "Asse até cozinhar.", "Sirva com arroz e brócolis."],
  ],
  [
    "Pudim de chia com frutas",
    "Lanche",
    ["Vegano", "Fibras"],
    310,
    15,
    [
      "Sementes de chia",
      "Leite ou bebida vegetal",
      "Banana",
      "Frutas vermelhas",
    ],
    [
      "Misture chia e leite.",
      "Refrigere por pelo menos 2 horas.",
      "Sirva com frutas.",
    ],
  ],
];

const recipe = (name, type, tags, calories, timeMinutes, ingredients) => [
  name,
  type,
  tags,
  calories,
  timeMinutes,
  ingredients,
  [
    `Separe e higienize os ingredientes de ${name.toLowerCase()}.`,
    type === "Café da manhã" || type === "Lanche"
      ? "Misture ou monte os ingredientes até obter uma porção uniforme."
      : "Cozinhe ou grelhe os ingredientes até ficarem completamente preparados.",
    "Ajuste os temperos e sirva na hora.",
  ],
];

const extraRecipes = [
  recipe(
    "Mingau de aveia com maçã",
    "Café da manhã",
    ["Fibras", "Rápido"],
    360,
    12,
    ["Aveia", "Leite", "Maçã", "Canela"],
  ),
  recipe(
    "Tapioca de queijo e tomate",
    "Café da manhã",
    ["Prático", "Vegetariano"],
    340,
    10,
    ["Goma de tapioca", "Queijo minas", "Tomate", "Orégano"],
  ),
  recipe(
    "Cuscuz com ovo e legumes",
    "Café da manhã",
    ["Baixo custo", "Proteína"],
    430,
    18,
    ["Flocos de milho", "Ovo", "Cenoura", "Ervilha"],
  ),
  recipe(
    "Panqueca de banana e aveia",
    "Café da manhã",
    ["Sem açúcar", "Fibras"],
    380,
    15,
    ["Banana", "Ovos", "Aveia", "Canela"],
  ),
  recipe(
    "Pão de queijo de frigideira",
    "Café da manhã",
    ["Rápido", "Sem glúten"],
    350,
    10,
    ["Ovo", "Polvilho", "Queijo", "Iogurte"],
  ),
  recipe(
    "Bowl de mamão com sementes",
    "Café da manhã",
    ["Fibras", "Natural"],
    300,
    8,
    ["Mamão", "Iogurte", "Sementes de abóbora", "Aveia"],
  ),
  recipe(
    "Crepioca de frango",
    "Café da manhã",
    ["Alta proteína", "Prático"],
    410,
    15,
    ["Ovo", "Tapioca", "Frango desfiado", "Ricota"],
  ),
  recipe(
    "Sanduíche de atum natural",
    "Café da manhã",
    ["Proteína", "Rápido"],
    390,
    12,
    ["Pão integral", "Atum", "Iogurte", "Alface"],
  ),
  recipe(
    "Overnight oats de cacau",
    "Café da manhã",
    ["Fibras", "Sem açúcar"],
    370,
    10,
    ["Aveia", "Leite", "Cacau", "Banana", "Chia"],
  ),
  recipe(
    "Vitamina de morango e aveia",
    "Café da manhã",
    ["Rápido", "Natural"],
    320,
    7,
    ["Morangos", "Leite", "Aveia", "Banana"],
  ),
  recipe(
    "Ovos mexidos com espinafre",
    "Café da manhã",
    ["Low carb", "Proteína"],
    280,
    10,
    ["Ovos", "Espinafre", "Tomate", "Azeite"],
  ),
  recipe(
    "Pão integral com ricota temperada",
    "Café da manhã",
    ["Leve", "Vegetariano"],
    310,
    8,
    ["Pão integral", "Ricota", "Cenoura", "Ervas"],
  ),
  recipe(
    "Bolo de caneca de banana",
    "Café da manhã",
    ["Rápido", "Sem açúcar"],
    360,
    8,
    ["Banana", "Ovo", "Aveia", "Cacau"],
  ),
  recipe(
    "Iogurte com manga e coco",
    "Café da manhã",
    ["Natural", "Sem glúten"],
    330,
    6,
    ["Iogurte", "Manga", "Coco ralado", "Chia"],
  ),
  recipe(
    "Batata-doce com cottage",
    "Café da manhã",
    ["Sustentável", "Proteína"],
    400,
    20,
    ["Batata-doce", "Queijo cottage", "Cebolinha", "Pimenta"],
  ),

  recipe(
    "Arroz integral com frango e brócolis",
    "Almoço",
    ["Marmita", "Alta proteína"],
    590,
    35,
    ["Arroz integral", "Frango", "Brócolis", "Cenoura"],
  ),
  recipe(
    "Carne moída com abóbora",
    "Almoço",
    ["Baixo custo", "Caseiro"],
    570,
    30,
    ["Carne moída", "Abóbora", "Cebola", "Salsinha"],
  ),
  recipe(
    "Lentilha com arroz e couve",
    "Almoço",
    ["Vegetariano", "Fibras"],
    540,
    35,
    ["Lentilha", "Arroz integral", "Couve", "Tomate"],
  ),
  recipe(
    "Macarrão integral com atum",
    "Almoço",
    ["Rápido", "Proteína"],
    610,
    25,
    ["Macarrão integral", "Atum", "Tomate", "Azeitona"],
  ),
  recipe(
    "Escondidinho de frango e mandioca",
    "Almoço",
    ["Caseiro", "Completo"],
    640,
    45,
    ["Frango", "Mandioca", "Tomate", "Queijo"],
  ),
  recipe("Quibe assado com salada", "Almoço", ["Prático", "Marmita"], 550, 40, [
    "Trigo para quibe",
    "Carne moída",
    "Hortelã",
    "Alface",
  ]),
  recipe(
    "Tofu grelhado com arroz e legumes",
    "Almoço",
    ["Vegano", "Proteína"],
    520,
    25,
    ["Tofu", "Arroz integral", "Abobrinha", "Cenoura"],
  ),
  recipe(
    "Bife acebolado com feijão",
    "Almoço",
    ["Caseiro", "Alta proteína"],
    630,
    30,
    ["Patinho", "Feijão", "Arroz", "Cebola"],
  ),
  recipe(
    "Salada de macarrão com frango",
    "Almoço",
    ["Prático", "Leve"],
    570,
    25,
    ["Macarrão integral", "Frango", "Tomate", "Milho"],
  ),
  recipe(
    "Arroz de forno com legumes",
    "Almoço",
    ["Vegetariano", "Aproveitamento"],
    500,
    35,
    ["Arroz cozido", "Abobrinha", "Cenoura", "Queijo"],
  ),
  recipe(
    "Moqueca leve de peixe",
    "Almoço",
    ["Sem glúten", "Proteína"],
    580,
    35,
    ["Peixe", "Tomate", "Pimentão", "Leite de coco"],
  ),
  recipe(
    "Frango ao curry com arroz",
    "Almoço",
    ["Aromático", "Marmita"],
    610,
    30,
    ["Frango", "Arroz integral", "Curry", "Iogurte"],
  ),
  recipe("Feijão branco com legumes", "Almoço", ["Vegano", "Fibras"], 490, 35, [
    "Feijão branco",
    "Cenoura",
    "Abobrinha",
    "Tomate",
  ]),
  recipe(
    "Nhoque de batata-doce",
    "Almoço",
    ["Vegetariano", "Caseiro"],
    560,
    45,
    ["Batata-doce", "Farinha", "Molho de tomate", "Manjericão"],
  ),
  recipe(
    "Bowl mexicano de feijão",
    "Almoço",
    ["Vegano", "Sem lactose"],
    530,
    20,
    ["Feijão preto", "Milho", "Arroz", "Abacate", "Tomate"],
  ),
  recipe(
    "Panqueca integral de carne",
    "Almoço",
    ["Marmita", "Completo"],
    600,
    40,
    ["Farinha integral", "Carne moída", "Tomate", "Ricota"],
  ),
  recipe(
    "Cevadinha com cogumelos",
    "Almoço",
    ["Vegetariano", "Fibras"],
    510,
    35,
    ["Cevadinha", "Cogumelos", "Cenoura", "Parmesão"],
  ),
  recipe(
    "Frango xadrez com legumes",
    "Almoço",
    ["Prático", "Proteína"],
    590,
    30,
    ["Frango", "Pimentão", "Cebola", "Amendoim"],
  ),
  recipe(
    "Salada morna de batata e ovo",
    "Almoço",
    ["Leve", "Baixo custo"],
    470,
    25,
    ["Batata", "Ovos", "Vagem", "Mostarda"],
  ),
  recipe(
    "Arroz integral com sardinha",
    "Almoço",
    ["Ômega 3", "Baixo custo"],
    560,
    20,
    ["Arroz integral", "Sardinha", "Tomate", "Cebola"],
  ),

  recipe(
    "Frango assado com batata",
    "Jantar",
    ["Caseiro", "Completo"],
    620,
    45,
    ["Coxa de frango", "Batata", "Cenoura", "Alecrim"],
  ),
  recipe(
    "Sopa de legumes com carne",
    "Jantar",
    ["Conforto", "Fibras"],
    430,
    40,
    ["Patinho", "Abóbora", "Cenoura", "Chuchu"],
  ),
  recipe("Omelete de legumes", "Jantar", ["Leve", "Low carb"], 320, 15, [
    "Ovos",
    "Abobrinha",
    "Cenoura",
    "Queijo",
  ]),
  recipe(
    "Tilápia grelhada com purê",
    "Jantar",
    ["Proteína", "Sem glúten"],
    560,
    30,
    ["Tilápia", "Batata", "Leite", "Brócolis"],
  ),
  recipe(
    "Risoto de frango e ervilhas",
    "Jantar",
    ["Completo", "Caseiro"],
    600,
    40,
    ["Arroz arbóreo", "Frango", "Ervilhas", "Parmesão"],
  ),
  recipe(
    "Abobrinha recheada com carne",
    "Jantar",
    ["Low carb", "Alta proteína"],
    480,
    35,
    ["Abobrinha", "Carne moída", "Tomate", "Queijo"],
  ),
  recipe(
    "Berinjela à parmegiana leve",
    "Jantar",
    ["Vegetariano", "Forno"],
    510,
    45,
    ["Berinjela", "Molho de tomate", "Muçarela", "Aveia"],
  ),
  recipe(
    "Caldo de mandioca com frango",
    "Jantar",
    ["Conforto", "Proteína"],
    520,
    40,
    ["Mandioca", "Frango", "Couve", "Cebola"],
  ),
  recipe(
    "Legumes assados com grão-de-bico",
    "Jantar",
    ["Vegano", "Fibras"],
    460,
    35,
    ["Grão-de-bico", "Abóbora", "Brócolis", "Pimentão"],
  ),
  recipe(
    "Carne desfiada com purê de abóbora",
    "Jantar",
    ["Caseiro", "Sem glúten"],
    570,
    50,
    ["Carne bovina", "Abóbora", "Cebola", "Salsinha"],
  ),
  recipe("Sopa cremosa de lentilha", "Jantar", ["Vegano", "Fibras"], 410, 35, [
    "Lentilha",
    "Cenoura",
    "Tomate",
    "Batata",
  ]),
  recipe(
    "Espaguete de abobrinha com frango",
    "Jantar",
    ["Low carb", "Leve"],
    440,
    25,
    ["Abobrinha", "Frango", "Tomate", "Manjericão"],
  ),
  recipe(
    "Arroz cremoso de camarão",
    "Jantar",
    ["Proteína", "Especial"],
    620,
    35,
    ["Camarão", "Arroz", "Tomate", "Leite de coco"],
  ),
  recipe(
    "Torta integral de legumes",
    "Jantar",
    ["Vegetariano", "Forno"],
    490,
    50,
    ["Farinha integral", "Ovos", "Abobrinha", "Cenoura"],
  ),
  recipe(
    "Polenta com ragu de carne",
    "Jantar",
    ["Caseiro", "Conforto"],
    610,
    45,
    ["Fubá", "Carne moída", "Tomate", "Parmesão"],
  ),
  recipe("Curry de grão-de-bico", "Jantar", ["Vegano", "Aromático"], 500, 30, [
    "Grão-de-bico",
    "Leite de coco",
    "Curry",
    "Espinafre",
  ]),
  recipe(
    "Peixe ensopado com tomate",
    "Jantar",
    ["Leve", "Sem lactose"],
    450,
    30,
    ["Filé de peixe", "Tomate", "Pimentão", "Cebola"],
  ),
  recipe(
    "Batata recheada com frango",
    "Jantar",
    ["Prático", "Proteína"],
    550,
    35,
    ["Batata", "Frango", "Milho", "Requeijão"],
  ),
  recipe("Salada completa com ovo", "Jantar", ["Leve", "Rápido"], 390, 15, [
    "Folhas verdes",
    "Ovos",
    "Grão-de-bico",
    "Tomate",
  ]),
  recipe("Lasanha de berinjela", "Jantar", ["Vegetariano", "Forno"], 520, 55, [
    "Berinjela",
    "Molho de tomate",
    "Ricota",
    "Muçarela",
  ]),

  recipe(
    "Maçã assada com canela",
    "Lanche",
    ["Sem açúcar", "Fibras"],
    180,
    20,
    ["Maçã", "Canela", "Castanhas"],
  ),
  recipe(
    "Palitos de cenoura com homus",
    "Lanche",
    ["Vegano", "Fibras"],
    240,
    12,
    ["Cenoura", "Grão-de-bico", "Tahine", "Limão"],
  ),
  recipe(
    "Mix de castanhas e frutas secas",
    "Lanche",
    ["Prático", "Energia"],
    280,
    3,
    ["Castanha", "Amêndoa", "Uva-passa", "Semente de abóbora"],
  ),
  recipe(
    "Pipoca de panela com ervas",
    "Lanche",
    ["Baixo custo", "Rápido"],
    210,
    10,
    ["Milho de pipoca", "Azeite", "Orégano"],
  ),
  recipe("Muffin integral de cenoura", "Lanche", ["Fibras", "Forno"], 290, 30, [
    "Cenoura",
    "Ovo",
    "Farinha integral",
    "Aveia",
  ]),
  recipe(
    "Pasta de ricota com torradas",
    "Lanche",
    ["Proteína", "Prático"],
    260,
    10,
    ["Ricota", "Iogurte", "Ervas", "Pão integral"],
  ),
  recipe(
    "Banana congelada com cacau",
    "Lanche",
    ["Sem açúcar", "Natural"],
    220,
    5,
    ["Banana", "Cacau", "Pasta de amendoim"],
  ),
  recipe("Edamame temperado", "Lanche", ["Vegano", "Proteína"], 190, 8, [
    "Edamame",
    "Limão",
    "Gergelim",
    "Sal",
  ]),
  recipe(
    "Bolinho de grão-de-bico",
    "Lanche",
    ["Vegetariano", "Fibras"],
    270,
    30,
    ["Grão-de-bico", "Cenoura", "Aveia", "Salsinha"],
  ),
  recipe("Pera com queijo branco", "Lanche", ["Rápido", "Sem glúten"], 230, 4, [
    "Pera",
    "Queijo branco",
    "Nozes",
  ]),
  recipe("Chips de batata-doce", "Lanche", ["Forno", "Sem lactose"], 200, 25, [
    "Batata-doce",
    "Azeite",
    "Páprica",
  ]),
  recipe(
    "Creme de abacate com limão",
    "Lanche",
    ["Vegano", "Natural"],
    250,
    6,
    ["Abacate", "Limão", "Cacau", "Chia"],
  ),
  recipe(
    "Barrinha caseira de aveia",
    "Lanche",
    ["Prático", "Fibras"],
    300,
    25,
    ["Aveia", "Banana", "Amendoim", "Coco"],
  ),
  recipe(
    "Tomate-cereja com muçarela",
    "Lanche",
    ["Rápido", "Vegetariano"],
    210,
    5,
    ["Tomate-cereja", "Muçarela", "Manjericão"],
  ),
  recipe(
    "Iogurte com pêssego e linhaça",
    "Lanche",
    ["Fibras", "Natural"],
    280,
    5,
    ["Iogurte", "Pêssego", "Linhaça", "Aveia"],
  ),
  recipe(
    "Ovo cozido com páprica",
    "Lanche",
    ["Proteína", "Low carb"],
    160,
    12,
    ["Ovos", "Páprica", "Cebolinha"],
  ),
  recipe(
    "Sanduíche de pasta de grão-de-bico",
    "Lanche",
    ["Vegano", "Prático"],
    340,
    15,
    ["Pão integral", "Grão-de-bico", "Tahine", "Alface"],
  ),
  recipe(
    "Picolé de iogurte e frutas",
    "Lanche",
    ["Natural", "Sem açúcar"],
    190,
    10,
    ["Iogurte", "Morangos", "Banana", "Chia"],
  ),
  recipe(
    "Bolinha energética de tâmaras",
    "Lanche",
    ["Vegano", "Sem forno"],
    260,
    15,
    ["Tâmaras", "Aveia", "Cacau", "Castanhas"],
  ),
  recipe(
    "Torrada integral com guacamole",
    "Lanche",
    ["Fibras", "Vegetariano"],
    290,
    10,
    ["Pão integral", "Abacate", "Tomate", "Limão"],
  ),
  recipe(
    "Mousse de cacau com banana",
    "Lanche",
    ["Sem açúcar", "Natural"],
    240,
    8,
    ["Banana", "Cacau", "Iogurte", "Canela"],
  ),
  recipe("Grão-de-bico crocante", "Lanche", ["Vegano", "Fibras"], 230, 35, [
    "Grão-de-bico",
    "Azeite",
    "Páprica",
    "Cominho",
  ]),
  recipe(
    "Smoothie de abacaxi e hortelã",
    "Lanche",
    ["Natural", "Refrescante"],
    210,
    6,
    ["Abacaxi", "Hortelã", "Iogurte", "Gengibre"],
  ),
];

const recipes = [...starterRecipes, ...extraRecipes];

if (recipes.length !== 90) {
  throw new Error(
    `Seed invalido: esperado 90 receitas, recebido ${recipes.length}.`,
  );
}

async function main() {
  for (const [
    name,
    type,
    tags,
    calories,
    timeMinutes,
    ingredients,
    steps,
  ] of recipes) {
    await prisma.recipe.upsert({
      where: { name },
      update: {
        type,
        tags,
        calories,
        timeMinutes,
        ingredients,
        steps,
        active: true,
      },
      create: { name, type, tags, calories, timeMinutes, ingredients, steps },
    });
  }
}

main()
  .catch((error) => {
    console.error(error);
    process.exitCode = 1;
  })
  .finally(async () => prisma.$disconnect());
